#!/usr/bin/env sh

DO=HELP
FORCE=N
FILENAME=
REMOTE=origin
MERGED=--

case "$1" in
    list)    DO=LIST  ;;
    clean)   DO=CLEAN ;;
    help)    DO=HELP  ;;
    *)
    echo "Bad command $1"
    DO=HELP ;;
esac

shift

while [ "$#" \!= 0 ]; do
    CURRENT="$1"

    case "$CURRENT" in
        -f|--file)    FILENAME="$2"; shift ;;
        -n|--dry-run) FORCE=N ;;
        -c|--clean)   FORCE=Y ;;
        -r|--remote)  REMOTE="$2"; shift ;;
        --merged)     MERGED="--merged" ;;
        --no-merged)  MERGED="--no-merged" ;;
        --)           shift; break ;;
        -*)
             echo "Bad parameter $CURRENT"
             DO=HELP
             break;
             ;;
        *) break ;;
    esac
    shift
done

if [ "${DO}" = HELP ]; then
    cat <<EOF
Usage: $0 action [options] [--] [branch1 [branch2 [...]]]

Where actions include:
  list         List branch in origin (or specified remote)
  clean        Remove the specified branch from origin (or specified remote)
  help         Display this message

Where options include:
--dry-run or -n             Don't delete, only show what would be deleted.
--clean or -c               Actually do deletion of remote branches.
--file [FILE] or -f [FILE]  Specify the file to read/write branch list from/to.
                            Defaults to STDIN/STDOUT
--remote [REMOTE] or -r [REMOTE]   Sets the remote repository to use.
                            Defaults to origin
--merged                    Limit to items merged to the current commit.
--no-merged                 Limit to items NOT merged to the current commit.

--                          Not an argument, but rather an indication that all
                            following items are branches to clean.

Notes on cleaning up remote branches:

clean is a dangerous operation! Make sure that what you specify
is what you actually want deleted!

clean wil *NOT* remove develop or master even if directed to.
EOF
    exit 1
fi

if [ "${DO}" = LIST ]; then
    git fetch "$REMOTE" --prune > /dev/null 2>&1

    if [ ":${FILENAME}" = : ]; then
        git branch -r "$MERGED" | grep "$REMOTE" | cut -d / -f 2-
    else
        git branch -r "$MERGED" | grep "$REMOTE" | cut -d / -f 2- > "${FILENAME}"
    fi
    exit 0;
fi

function get_list () {
    local FILE="$1"
    shift

    MERGED_FILE="`mktemp "${TMPDIR}/repo.XXXXX"`"
    git branch -r "$MERGED" | grep "$REMOTE" | cut -d / -f 2- | egrep -v "^(master|develop)$" | egrep -v "^HEAD " > "${MERGED_FILE}"

    if [ ":${MERGED}" = ":--" ]; then
        MERGED_LIST=N
    else
        MERGED_LIST=Y
    fi

    while [ "$#" \!= 0 ]; do
        echo "$1" | egrep -v "^(master|develop)$" | egrep -v "^HEAD "
        shift
        false
    done

    # HACK -- while resets variables on completion.
    if [ $? = 1 ]; then
        MERGED_LIST=N
    fi

    if [ ":${FILE}" \!= : ]; then
        MERGED_LIST=N
        cat "${FILE}" | egrep -v "^(master|develop)$" | egrep -v "^HEAD "
    fi

    if [ ":${MERGED_LIST}" = ":Y" ]; then
        cat "${MERGED_FILE}"
    fi

    rm "${MERGED_FILE}"
}

if [ "${DO}" = CLEAN -a "${FORCE}" = N ]; then
    FOUND_SOMETHING=N
    get_list "${FILENAME}" "$@" | while read BRANCH; do
        echo "Would delete branch: ${BRANCH}"
        false
    done

    # HACK -- while resets variables on completion.
    if [ $? = 1 ]; then
        FOUND_SOMETHING=Y
    fi

    if [ ":${FOUND_SOMETHING}" = ":Y" ]; then
        echo "To actually delete these use the --clean or the -c switches"
    else
        echo "Nothing found or specified to delete."
    fi
    exit 0;
fi

if [ "${DO}" = CLEAN -a "${FORCE}" = Y ]; then
    echo Cleaning in 5 seconds, ctrl-c to stop
    seq 5 -1 1 | while read I; do echo "$I "; sleep 1; done
    echo Cleaning
    get_list "${FILENAME}" "$@" | while read BRANCH; do git push "$REMOTE" ":${BRANCH}"; done
    git fetch "${REMOTE}" --prune > /dev/null 2>&1
    exit 0;
fi


